version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    tty: true
    command: sh -c "python3 manage.py migrate && 
                    python3 manage.py csu && 
                    python3 manage.py fill_db && 
                    python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    volumes:
      - .:/app
    depends_on:
      - celery
      - redis
      - app

volumes:
  pg_data:
